[package]
name = "xml-coding-challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanf = "1.2.1"
xml-schema = "0.2"
xml-schema-derive = "0.2"
yaserde = "0.8"
yaserde_derive = "0.8"
